More scripts and aliases

diff --git a/.local/bin/mansplain b/.local/bin/mansplain
--- a/.local/bin/mansplain
+++ b/.local/bin/mansplain
@@ -1,2 +1,6 @@
-#!/bin/sh
-man -k . | sort | rofi -dmenu | awk '{print $1}' | xargs -r man -t | ps2pdf - | zathura -
+#!/usr/bin/env bash
+
+function fail () { dunstify 'Failed to load the manual page !'; exit; }
+
+pdf=$(man -k . | sort | rofi -dmenu | awk '{print $1}' | xargs -r man -t)
+[[ ! -z "$pdf" ]] && echo "$pdf" | ps2pdf - | zathura - || fail
